[ARC-1888]Feature/add layouts
giorgiqemoklidze/QuizApp pull request #1
Opened 2021-11-12 11:02 UTC by giorgiqemoklidze

https://spaceneobank.atlassian.net/browse/ARC-1877

2021-11-15 09:39 UTC, AnaRusadze requested changes

2021-11-15 09:39 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/ui/customview/ArkBackground.kt
> +class ArkBackground @JvmOverloads constructor(
Arc იწერება

2021-11-15 09:39 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/ui/customview/ArkBackground.kt
> +            radius = getDimensionPixelSize(R.styleable.BackgroundCV_cv_radius, 160).toFloat()
160 და 100 კონსტანტ ცვლადებში გაიტანე და default radius და default overflow დაარქვი

2021-11-15 09:39 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/ui/customview/ArkBackground.kt
> +    private val oval: RectF = RectF(0f, 0f, 0f, 0f)
იმისთვის, რომ ორი rectის ობიექტი არ დაიხატოს, შეგიძლია path0-გამოიყენო, lineTo და arcTo ფუნქციებით და ისე შემოსაზღვრო ფორმა

2021-11-15 14:07 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/quizapp/ui/customview/ArkBackground.kt
> +class ArkBackground @JvmOverloads constructor(
done

2021-11-15 14:07 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/quizapp/ui/customview/ArkBackground.kt
> +            radius = getDimensionPixelSize(R.styleable.BackgroundCV_cv_radius, 160).toFloat()
done

2021-11-15 14:07 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/quizapp/ui/customview/ArkBackground.kt
> +    private val oval: RectF = RectF(0f, 0f, 0f, 0f)
done

2021-11-16 06:54 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-17 09:28 UTC, AnaRusadze requested changes

2021-11-17 09:28 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/ui/customview/ArcBackground.kt
> +        path.arcTo(-overFlow, 0f, measuredWidth.toFloat() + overFlow, 2 * radius, 180f, 180f, false)
path.apply{}

2021-11-17 09:28 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/ui/customview/ArcBackground.kt
> +    private var radius = 0f
DEF_RADIUS
DEF_OVERFLOW

2021-11-17 13:00 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/quizapp/ui/customview/ArcBackground.kt
> +        path.arcTo(-overFlow, 0f, measuredWidth.toFloat() + overFlow, 2 * radius, 180f, 180f, false)
done

2021-11-17 13:00 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/quizapp/ui/customview/ArcBackground.kt
> +    private var radius = 0f
done

2021-11-17 13:20 UTC, AleksandreGalogreBaramidze approved these changes

2021-11-17 13:25 UTC, AnaRusadze approved these changes

2021-11-17 13:25 UTC, merged