[ARC-1891]question fragment added and some function names refactored
giorgiqemoklidze/QuizApp pull request #4
Opened 2021-12-01 11:53 UTC by giorgiqemoklidze

https://spaceneobank.atlassian.net/browse/ARC-1891

2021-12-01 11:58 UTC, GiorgiMamagulashvili16 requested changes

2021-12-01 11:58 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/ui/home/HomeFragment.kt
> +        viewModel.setUserName()
with()

2021-12-01 12:04 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/quizapp/ui/home/HomeFragment.kt
> +        viewModel.setUserName()
done

2021-12-01 12:37 UTC, GiorgiMamagulashvili16 approved these changes

2021-12-06 10:54 UTC, AleksandreGalogreBaramidze approved these changes

2021-12-06 14:19 UTC, AnaRusadze approved these changes

2021-12-06 14:19 UTC, merged